set(CMAKE_CXX_STANDARD 17)

if(${CMAKE_CXX_STANDARD} LESS_EQUAL 17)
    set(CMAKE_CXX_STANDARD 17)
endif()

set(LIBPRGE_CPP_STANDARD ${CMAKE_CXX_STANDARD})

set(LIBPRGE_VERSION_MAJOR 0)
set(LIBPRGE_VERSION_MINOR 0)
set(LIBPRGE_VERSION_PATCH 0)
set(LIBPRGE_VERSION_DATES 20250115)
set(LIBPRGE_VERSION_STRING "${LIBPRGE_VERSION_MAJOR}.${LIBPRGE_VERSION_MINOR}.${LIBPRGE_VERSION_PATCH}.${LIBPRGE_VERSION_DATES}")

string(TOLOWER ${CMAKE_SYSTEM_NAME} LIBPRGE_SYSTEM_NAME)
string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} LIBPRGE_SYSTEM_PROCESSOR)
string(TOLOWER ${CMAKE_BUILD_TYPE} LIBPRGE_SYSTEM_BUILD_TYPE)

if(LIBPRGE_SYSTEM_BUILD_TYPE STREQUAL "release")
    set(LIBPRGE_IS_DEBUG false)
    if(LIBPRGE_CONF_GODOTCPP_FOR_EDITOR)
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_release godot-cpp::editor)
    else()
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_release)
    endif()
elseif(LIBPRGE_SYSTEM_BUILD_TYPE STREQUAL "minsizerel")
    set(LIBPRGE_IS_DEBUG false)
    if(LIBPRGE_CONF_GODOTCPP_FOR_EDITOR)
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_release godot-cpp::editor)
    else()
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_release)
    endif()
else()
    set(LIBPRGE_IS_DEBUG true)
    if(LIBPRGE_CONF_GODOTCPP_FOR_EDITOR)
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_debug godot-cpp::editor)
    else()
        set(LIBPRGE_GODOTCPP_TARGETS godot-cpp::template_debug)
    endif()
endif()

# start: INCLUDE SOME DIRS?
# end: INCLUDE SOME DIRS?

# overwrite
if(${LIBPRGE_SYSTEM_NAME} STREQUAL "darwin")
    set(LIBPRGE_SYSTEM_NAME "macos")
endif()

set(LIBPRGE_OUTPUT "${LIBPRGE_SYSTEM_NAME}_${LIBPRGE_SYSTEM_PROCESSOR}/${LIBPRGE_SYSTEM_BUILD_TYPE}")

message(NOTICE "-- ${PROJECT_NAME}:\n   configuring ${PROJECT_NAME} v${LIBPRGE_VERSION_STRING} using c++${LIBPRGE_CPP_STANDARD} targeting ${LIBPRGE_SYSTEM_NAME} ${LIBPRGE_SYSTEM_PROCESSOR} ${LIBPRGE_SYSTEM_BUILD_TYPE}")

set(LIBPRGE_OUTPUT_EXAMPLE_DIR "${CMAKE_SOURCE_DIR}/example/addons/libprge/bin/${LIBPRGE_SYSTEM_NAME}_${LIBPRGE_SYSTEM_PROCESSOR}/${LIBPRGE_SYSTEM_BUILD_TYPE}")

if(LIBPRGE_OUTPUT_EXAMPLE_DIR_IS)
    message(NOTICE "-- ${PROJECT_NAME}:\n   using LIBPRGE_OUTPUT_EXAMPLE_DIR_IS, the output will be \"${LIBPRGE_OUTPUT_EXAMPLE_DIR}\"")
    set(EXECUTABLE_OUTPUT_PATH         "${LIBPRGE_OUTPUT_EXAMPLE_DIR}")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${LIBPRGE_OUTPUT_EXAMPLE_DIR}")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${LIBPRGE_OUTPUT_EXAMPLE_DIR}")
    set(CMAKE_PDB_OUTPUT_DIRECTORY     "${LIBPRGE_OUTPUT_EXAMPLE_DIR}")
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${LIBPRGE_OUTPUT_EXAMPLE_DIR}")
endif()
